name: docker build

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build
      run: docker build -t xinpascal/riscv-gnu-toolchain:rvv-intrinsic .
    - name: Deploy
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push xinpascal/riscv-gnu-toolchain:rvv-intrinsic
